name: stryde_mobile_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.0
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  google_fonts: ^5.1.0
  file_picker: ^8.0.0+1
  another_flushbar: ^1.12.30
  phosphor_flutter: ^2.1.0
  fpdart: ^1.1.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  smooth_page_indicator: ^1.2.0+3
  pinput: ^5.0.0
  image_picker: ^1.0.8
  image_cropper: ^6.0.0
  grouped_list: ^6.0.0
  flutter_switch: ^0.3.2
  dio: ^5.5.0+1
  video_player: ^2.9.1
  flutter_rating_bar: ^4.0.1
  flutter_carousel_widget: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/stryde_app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "lib/assets/icons/stryde_adaptive.png"
  min_sdk_android: 21 

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#000000"
  color_dark: "#000000"
  image: "lib/assets/images/splash_center.png"

  android_12:
    color: "#000000"
    color_dark: "#000000"
    icon_background_color: "#000000"
    image: "lib/assets/icons/stryde_adaptive.png"

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/

